### ISSUE TITLE
Fail to install

### ISSUE THREAD

**Issue by Trevoke** [One-com/react-truncate#1]
Here's the error log:

> npm ERR! Linux 4.2.0-36-generic
> npm ERR! argv "/home/trevoke/.nvm/versions/node/v4.2.3/bin/node" "/home/trevoke/.nvm/versions/node/v4.2.3/bin/npm" "i" "--save" "react-truncate"
> npm ERR! node v4.2.3
> npm ERR! npm  v2.14.7
> npm ERR! code EPEERINVALID
> 
> npm ERR! peerinvalid The package react@15.0.2 does not satisfy its siblings' peerDependencies requirements!
> npm ERR! peerinvalid Peer react-addons-css-transition-group@15.0.2 wants react@^15.0.2
> npm ERR! peerinvalid Peer react-dom@15.0.2 wants react@^15.0.2
> npm ERR! peerinvalid Peer react-masonry-component@4.0.0 wants react@>= 0.14.0
> npm ERR! peerinvalid Peer react-modal@1.2.1 wants react@^0.14.0 || ^15.0.0-0
> npm ERR! peerinvalid Peer react-redux@4.4.4 wants react@^0.14.0 || ^15.0.0-0
> npm ERR! peerinvalid Peer react-router@2.4.0 wants react@^0.14.0 || ^15.0.0
> npm ERR! peerinvalid Peer react-slick@0.12.0 wants react@^0.14.0 || ^15.0.1
> npm ERR! peerinvalid Peer react-telephone-input@3.2.4 wants react@>=0.14.0 || ^15.0.0
> npm ERR! peerinvalid Peer redux-devtools@3.2.0 wants react@^0.14.0 || ^15.0.0-rc.1
> npm ERR! peerinvalid Peer react-addons-test-utils@15.0.2 wants react@^15.0.2
> npm ERR! peerinvalid Peer react-ellipsify@0.5.0 wants react@>= 0.13 < 1.0.0
> npm ERR! peerinvalid Peer redbox-react@1.2.6 wants react@^0.14.0 || ^15.0.0
> npm ERR! peerinvalid Peer redux-devtools-log-monitor@1.0.11 wants react@^0.14.0 || ^15.0.0-0
> npm ERR! peerinvalid Peer redux-devtools-dock-monitor@1.1.1 wants react@^0.14.0 || ^15.0.0-0
> npm ERR! peerinvalid Peer enzyme@2.3.0 wants react@0.13.x || 0.14.x || ^15.0.0-0

I'm not entirely certain which part of my stack it doesn't support.

**Comment by gustavnikolaj** [comment]
I'm very certain that this is not related to react-truncate. We are not mentioning anything about dependencies or peer dependencies in the package.json file (which might very well be a problem - but an unrelated one :-)).

From looking at the output it seems that `react-ellipsify` is the cause of your problem, as it requires a version of react higher than 0.13 and lower than 1.0.

> npm ERR! peerinvalid Peer react-ellipsify@0.5.0 wants react@>= 0.13 < 1.0.0

**Comment by Trevoke** [comment]
I'm terribly sorry, that was a side effect of react-ellipsify failing to install but not failing cleanly (I tried seven or eight packages and admittely only decided to open issues on them when I realized that none of them worked cleanly).

react-truncate did work, though I have a problem with it and will open an issue about it now.
