### ISSUE TITLE
line break is not being maintained

### ISSUE THREAD

**Issue by DiegoZoracKy** [One-com/react-truncate#18]
If the text contains some kind of line break (\n, <br/> or other block-level element), it is not being maintained, and we are ending up with a text in only one line.

**Comment by PabloSichert** [comment]
Correct, those are currently not handled.

I will let you know when I have progressed on that, might be this weekend.

**Comment by PabloSichert** [comment]
Landed and available in `v2`.

Please note that for consistency only `<br/>` tags trigger newlines and you might need to map your plain text source from `\n` to `<br/>`.
