### ISSUE TITLE
Toggling truncation off hides all text

### ISSUE THREAD

**Issue by yoadsn** [One-com/react-truncate#23]
Hello,
Perhaps I misunderstood the documentation but I have made sure to re-read it including the relevant source code.
For some reason, when setting `lines` to a falsy values or value < 1 all text is hidden.
I have created this short example to demonstrate:

http://www.webpackbin.com/Vywx9ZEZf

I figured this could be caused by a change introduced not long ago on #21 - Where this change to the `render()` method was made:
```
let text = children;
```
to
```
let text;
```

When looking in the React Dev Tools - the span with the "children" text appears, but the actual DOM does not contain the element. I think it has something to do with the removal of this node in ComponentDidMount.

Hope this is something simple I misunderstood..
Thanks!

**Comment by PabloSichert** [comment]
You are correct in your assumptions an this is indeed a bug. I assume I introduced this regression in https://github.com/One-com/react-truncate/pull/21.

Will keep you updated on the progress - thanks for reporting!

**Comment by PabloSichert** [comment]
Fixed as of `v2.0.2`.
