### ISSUE TITLE
Exception when text width is equal to parent container width

### ISSUE THREAD

**Issue by sulliedjar** [One-com/react-truncate#25]
Hello,

I have found a little bug that makes Truncate component break when the text width is equal to the parent container width.

In getLines() method, the line text width is measured and compared with container width. If text width is equal or greater than container the text is broken in multiple lines:

```
if (measureWidth(resultLine) < targetWidth) {
    if (textLines.length === 1) {
        // Line is end of text and fits without truncating //
        didTruncate = false;

        lines.push(resultLine);
        break;
    }
}
```

However, when the library try to determine when the line breaks, it repeats the same if-condition but adding equal operator:

```
if (measureWidth(testLine) <= targetWidth) {
    lower = middle + 1;
} else {
    upper = middle - 1;
}
```

If both widths are equal, _lower_ value is equal to _textWords_ length, making the following line to be empty (_textLines[0]_) and throwing an exception (_Cannot read property 'length' of undefined_):

```
const textWords = textLines[0];

// Handle newline
if (textWords.length === 0) {
    lines.push();
    textLines.shift();
    line--;
    continue;
}
```

Please review the code to make the truncate component works correctly when the width of text and parent container is equal.

Thanks!

**Comment by PabloSichert** [comment]
Thank you for reporting!

Fixed in `v2.0.3` with 27a80c7.
