### ISSUE TITLE
Code having memory leak, it is beign rerendered again and again

### ISSUE THREAD

**Issue by Param-Harrison** [One-com/react-truncate#27]
Simple way to debug this,
Put a console.log  inside render method, it will be called every second continuously which causes the browser tab to go unresponsive after some point.

**Comment by PabloSichert** [comment]
Could you provide more info about how you used the component and which props you gave it?

**Comment by Param-Harrison** [comment]
Hey actually, the <ReadMore /> component snippet is causing the memory leak, not in the Truncate library.

Example, if we pass onTruncate function through ReadMore, it causes memory leak. It continuously calling the same function again and again.

**Comment by PabloSichert** [comment]
Thanks! Fixed the demo.

**Comment by icd2k3** [comment]
This is still an issue and fairly easy to repro:

```
<Truncate lines={lines} onTruncate={(isTruncated) => {
    console.log(Math.random());
    this.setState({ isTruncated });
}}>
```

![image](https://user-images.githubusercontent.com/1458959/45367835-ff6f3480-b596-11e8-9395-cb70360ec04c.png)

**Comment by PabloSichert** [comment]
You must not call `setState` there unconditionally. Please have a look at https://github.com/One-com/react-truncate/commit/338707b8e97f8371683c604f7da41855644d0267

**Comment by shpindler** [comment]
In my case this is still memory leak:

```
onTruncate={(isTruncated) => {
  if (truncated !== isTruncated) {
    setTruncated(isTruncated)
  }
}}
```

Does adding condition really help you?
