### ISSUE TITLE
When letter-spacing is used, calculations are incorrect

### ISSUE THREAD

**Issue by atomiccupcake** [One-com/react-truncate#28]
I was having the same behavior described in https://github.com/One-com/react-truncate/issues/16, but while using web-safe font families. It turns out that when the css letter-spacing property is used, the component calculates it has room for more letters than it actually has room for.

It would be great if it could account for the pixels between letters. Thanks!

letter-spacing: 1px;
![image](https://cloud.githubusercontent.com/assets/6097979/21913505/1703e7f2-d8ea-11e6-9179-6f010bb93429.png)

letter-spacing: 0;

![not](https://cloud.githubusercontent.com/assets/6097979/21913597/7bb1aaea-d8ea-11e6-8e36-7184c4a20d4f.png)

**Comment by PabloSichert** [comment]
Hey, thanks for the fix! :sun_with_face: 

Released in `v2.0.4`

**Comment by atomiccupcake** [comment]
No problem! Thanks for the speedy merge!

**Comment by devwells** [comment]
Can you reopen this issue? The merge was rolled back because it caused an issue with something else. 

see commit cfc73e74d84a7a25eef75e5b3a42a21dbc8e841e

**Comment by PabloSichert** [comment]
@devwells I had looked over this PR too quickly: canvas text rendering (which is used to determine text width) neither supports letter spacing nor word spacing.
