### ISSUE TITLE
2.0.4 breaks measureWidth

### ISSUE THREAD

**Issue by namjul** [One-com/react-truncate#30]
I started using this great lib today but had a problems with it by not truncating to specified lines. It always truncated to more lines. I figured it this does not happen in 2.0.3.
When i revert the change made here: https://github.com/One-com/react-truncate/pull/29/commits/324d1bf7672245c30dc8d70a4fe1d88d27ea2629 it works again.

**Comment by PabloSichert** [comment]
Could you provide me with information about
- which font-related CSS rules are applied to your truncated text
- does `npm test` succeed locally for both revisions
- screenshots

So I can help figuring out where the problem might be

**Comment by namjul** [comment]
The test are working in master and v2.0.3
Here a gif with 2.0.4:
![output](https://cloud.githubusercontent.com/assets/328836/22283229/55d4510a-e2e1-11e6-9123-cceaa35b8c69.gif)
2.0.3:
![output2](https://cloud.githubusercontent.com/assets/328836/22283243/6abc9758-e2e1-11e6-8340-b7165c9682f4.gif)
The sample text has no styles applied.

**Comment by PabloSichert** [comment]
You are right, that commit 324d1bf is indeed faulty - which I'm going to revert on master.

The canvas [`context.font`](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/font) API does not expect a letter spacing / word spacing argument.

Looks like [this](http://stackoverflow.com/a/40469992) might be a viable workaround.

**Comment by namjul** [comment]
Thx for your fast response.

**Comment by eric-adstage** [comment]
@PabloSichert I just ran into the letter-spacing issue -- but not sure how the workaround you posted would apply here. Can you provide just a little more implementation detail? Thanks!

**Comment by thomasbaldwin** [comment]
@PabloSichert did this workaround ever get added?
http://stackoverflow.com/a/40469992

**Comment by PabloSichert** [comment]
I just tested some code:

```js
const canvas = document.createElement('canvas');
// document.body.append(canvas);
canvas.style.letterSpacing = '1px';
const context = canvas.getContext('2d');
context.measureText('foo');
```

It only affects the measuring in Chrome and only if you uncomment the second line, which means that it only works if the canvas is mounted to the DOM.

I wouldn't like to add code that is so dependent on the browser.

**Comment by arasmussen** [comment]
A better solution is to just manually calculate letter/word spacing in `measureWidth`.

```js
const targetStyle = window.getComputedStyle(target);
const letterSpacing = parseSpacing(targetStyle['letter-spacing']);
const wordSpacing = parseSpacing(targetStyle['word-spacing']);

const context = this.getCanvasContext(targetStyle);
const widthWithoutSpacing = context.measureText(text).width;
const widthWithSpacing = widthWithoutSpacing + (
  letterSpacing * (text.length - 1) +
  wordSpacing * (text.trim().split(/\s+/).length)
);
```

It works in all browsers, not just Chrome.

**Comment by arasmussen** [comment]
> But the behavior would diverge depending on the browser.

In theory, every browser should calculate letter/word spacing the same way. 

Manually calculating letter/word spacing, rather than relying on the browser to calculate it via `canvasContext.measureText`, works in every browser.

**Comment by PabloSichert** [comment]
I see your point, could be worth a shot.

Would you like to open a PR for that? I'd assist you in updating the test

**Comment by arasmussen** [comment]
Will take a look this weekend!
