### ISSUE TITLE
Width calculation is using the window width and not the parent element's width

### ISSUE THREAD

**Issue by drew-wallace** [One-com/react-truncate#32]
If I put a Truncate component in a div with padding, the generated elements are too long. Once I removed the padding, the generated elements fit to the appropriate number of lines.

It seems that you are calculating the appropriate width based on the width of the window and not the width of the Truncate component's parent. Consequently, if you calculate the width of the parent div instead of the window, you can rely on normal text wrapping instead of the current span + br pattern.

Example: go to your [demo page](http://www.webpackbin.com/Ek3NionEM), inside ReadMore.js, add this to div surrounding the Truncate component: `style={{padding: 15}}`

**Comment by PabloSichert** [comment]
The parent container width is read out using [`target.parentNode.getBoundingClientRect().width`](https://github.com/One-com/react-truncate/blob/master/src/Truncate.js#L130), not taking into account any padding.

You can work around that limitation using

```jsx
<ContainerWithPadding>
  <div>
    <Truncate>
      {content}
    </Truncate>
  </div>
</ContainerWithPadding>
```

---

It would be possible to add that functionality by reading [`window.getComputedStyle(target.parentNode).getPropertyValue('padding')`](https://developer.mozilla.org/en-US/docs/Web/API/Window/getComputedStyle).

I might implement this at a later time, but - please feel free to submit a PR.

**Comment by drew-wallace** [comment]
That did the trick. Thanks!

**Comment by PabloSichert** [comment]
Related: https://github.com/One-com/react-truncate/pull/38
