### ISSUE TITLE
Tests failing locally on fresh repo clone?

### ISSUE THREAD

**Issue by eric-adstage** [One-com/react-truncate#33]
Hey @PabloSichert,

Do you expect the current spec suite to pass locally? I'm getting several failures from a fresh clone of the repo.

I have fixes (pending comment/approval) for both the padding and font size issues, and I'd love to be able to write some specs to go along with them, but I need to start from a working test bed.

Any thoughts?

Screenshot:
![image](https://cloud.githubusercontent.com/assets/4295226/23450001/a35c20a0-fe0d-11e6-9f33-fcefff1259f9.png)

**Comment by PabloSichert** [comment]
Oh, that looks bad indeed - yes, they pass on my machine (Ubuntu).

I suspect it could be due to different default system fonts, as I don't tell in the tests which one to use.

Could you share your
- OS
- node version
- npm version

to test my assumption?

---

And, thank you for the contribution!

**Comment by capaj** [comment]
@eric-adstage they pass on my ubuntu as well-after I installed couple of OS dependencies:`sudo apt-get install libcairo2-dev libjpeg8-dev libpango1.0-dev libgif-dev build-essential g++`

```
capaj@capaj-i7-4771:~/git_projects/react-truncate$ nt

> react-truncate@2.0.5 test /home/capaj/git_projects/react-truncate
> mocha --compilers js:babel-core/register --require babel-polyfill



  <Truncate />
    ✓ should be a React component
    ✓ should render a span
    in a server environment
      ✓ should render initial static markup
    in a client environment
      ✓ should render without an error when the last line is exactly as wide as the container (138ms)
      ✓ should recalculate when resizing the window
      ✓ should clean up all event listeners on window when unmounting
      with a box of 85px mocked out
        ✓ should truncate text (78ms)
        ✓ should preserve newlines (74ms)
        ✓ should not add empty lines when text doesn't fill all lines (73ms)
        ✓ should not truncate at all if specified in lines prop (72ms)
        ✓ should end truncating when a single word is bigger than its line (72ms)
        ✓ should be able to use a react component as ellipsis (75ms)
        ✓ should update content when new children are passed in (74ms)
        onTruncate
          ✓ should invoke asynchronously (98ms)
          with Truncate.prototype.onTruncate mocked out
            ✓ should call with true when text was truncated (74ms)
            should call with false when text was not truncated because
              ✓ was disabled with lines prop (72ms)
              ✓ has shorter text than lines allow (78ms)
      innerText
        browser implements \n for <br/>
          ✓ should have newlines only at <br/>
        browser implements "" for <br/>
          ✓ should have newlines only at <br/>
    ellipsisWidth
      ✓ should equal node.offsetWidth


  20 passing (1s)

```

**Comment by PabloSichert** [comment]
@eric-adstage, could you check out branch [`fix/tests-font`](https://github.com/One-com/react-truncate/tree/fix/tests-font) locally to see if it passes on your machine?

Commit https://github.com/One-com/react-truncate/commit/d7dcdae40d82712aea5fa2f34f070bbf4b6cfa39 I landed on it might fix it.

**Comment by eric-adstage** [comment]
Hey @PabloSichert,

```
OS: OSX, 10.12.3 (16D32)
node: 5.6.0
npm: 3.6.0
```

I suspect you're onto something with the font issue, but unfortunately the build still fails with your latest branch, albeit 2 fewer spec failures. These, failing in my initial testing, now pass:

```
✓ should render without an error when the last line is exactly as wide as the container (2029ms)
✓ should be able to use a react component as ellipsis
```

I thought that perhaps the `<div>` in the "mocked out 85px box" tests needed its font specified as well, but in my initial tests, nothing changed when I specified the same 12px Times New Roman font as the canvas element uses.

**Comment by eric-adstage** [comment]
Just as a teaser, here's a div with both padding and letter-spacing:
![image](https://cloud.githubusercontent.com/assets/4295226/23476905/1e027c74-fe71-11e6-923f-7ce96e4f3def.png)

**Comment by PabloSichert** [comment]
Looks good!

I'll try to get an actual OSX machine to better reason about what's going on with the test suite.
