### ISSUE TITLE
do children allow array of nodes?

### ISSUE THREAD

**Issue by capaj** [One-com/react-truncate#35]
is it okay to do this?
```
<Truncate>
  <span dangerouslySetInnerHTML={{__html: draft.content}}/>
  <span dangerouslySetInnerHTML={{__html: draft.content}}/>
</Truncate>
```

**Comment by PabloSichert** [comment]
Yes, that's supposed to work.

By the docs:

children (example)
```jsx
<span>Some</span><span>siblings</span>
```

**Comment by capaj** [comment]
Thanks, I failed to spot it since it's weirdly formatted in the table.

**Comment by PabloSichert** [comment]
Agree on that, but unfortunately it's not possible to use the triple backticks inside a table with this flavor of Markdown.
