### ISSUE TITLE
Not compatible with IE9 and Safari6 when inside a Bootstrap Accordion

### ISSUE THREAD

**Issue by Mikeks81** [One-com/react-truncate#36]
So i know this is an edge case but these don't seem to play well OR i'm missing something. 

accordion issue with ie9 and safari 6 and lower
using bootstrap-react OR plain old bootstrap and react-truncate
when using react-truncate inside of a bootstrap react accordion you get an error from truncate:
‘“SCRIPT5009: ‘requestAnimationFrame’ is undefined “
except when you remove the Accordion attr of defaultActiveKey AND the panel EventKey attr which makes the accordion useless. 
With the error there it makes the panels unable to open and some text is not truncated. 

Now i'm not sure but i'm nearly positive i had this working last week. Any insight to help me with this would be awesome. Great Package but unfortunately i may not be able to use it due to people still using ie9... for whatever reason

**Comment by PabloSichert** [comment]
Could you try including this [`requestAnimationFrame` polyfill](https://gist.github.com/paulirish/1579671#file-raf-js) before your bundle and see if that helps?

**Comment by Mikeks81** [comment]
The rAF polyfill did the trick!!! Thanks so much

**Comment by PabloSichert** [comment]
You're welcome :D
