### ISSUE TITLE
Usage with react-autoscale

### ISSUE THREAD

**Issue by charlierudolph** [One-com/react-truncate#41]
I am using this library with [react-auto-scale](https://github.com/tomat/react-auto-scale). 

I am using this library inside an autoscaled div. When the window gets resized it appears the fact that its getting the [client bounding rectangle](https://github.com/One-com/react-truncate/blob/774782bd198f9aa73c28ee2fa3ba9ea9cb1b883d/src/Truncate.js#L130) causes it to mess the line-wrapping.

One easy solution for me here would be the ability to turn off the on resize listener. If you agree, I'd be happy to implement this and send a PR.

**Comment by PabloSichert** [comment]
```js
···

import Truncate from 'react-truncate';

···

Truncate.prototype.onResize = () => {};

···
```

would that work for you?
