### ISSUE TITLE
Webpackbin link is invalid

### ISSUE THREAD

**Issue by rockymeza** [One-com/react-truncate#43]
![image](https://cloud.githubusercontent.com/assets/21784/25020550/d14fb398-205c-11e7-9f44-28f51a53af08.png)

**Comment by PabloSichert** [comment]
Thanks for notifying!

Interesting that they just shut down old code without migrating it to their new service.

@gustavnikolaj could you update the link of this repo to https://www.webpackbin.com/bins/-KiANdakujgGkEW9wW1E?

**Comment by gustavnikolaj** [comment]
@PabloSichert Done :-) The bin seems to be noninteractive - is there something we can do to change that?

Also, is there any permission issue that meant that you couldn't update the link yourself, or were you just on your phone? :-) If it's a GitHub permissions issue, I'll try to fix it.

**Comment by PabloSichert** [comment]
What do you mean by noninteractive? I'm asking since the bin is supposed to toggle the text from truncated to full text (which works for me).

Was on the desktop version - there's no "edit" button for me, so looks like I'm missing a permission there.
