### ISSUE TITLE
prop-types module missing from peerDependencies

### ISSUE THREAD

**Issue by gmatroskin** [One-com/react-truncate#45]
Since `prop-types` was moved to `devDependencies` in 2.1.2, it should be added to `peerDependencies`.  I believe that may break compatibility with anyone running older versions of react (< 15.6).

**Comment by PabloSichert** [comment]
Thanks, good point!

Added in 04b8617 and released with [v2.1.3](https://github.com/One-com/react-truncate/releases/tag/v2.1.3).
