### ISSUE TITLE
renderLine is manulipating the text

### ISSUE THREAD

**Issue by DocCaliban** [One-com/react-truncate#48]
Not sure why you are adding line breaks here, if my input text didn't contain any line breaks why add them at all?  In my solution it makes for sloppy presentation.  I pasted an example of what a 3 line text blob looks like.

I could fix this on a local branch, just wondering what the underlying reason was.

Lorem ipsum dolor sit amet, consectetur
adipiscing 
elit, sed do eiusmod tempor incididunt ut 
labore 
et dolore magna aliqua. Ut enim ad 
minim

```
    renderLine(line, i, arr) {
        if (i === arr.length - 1) {
            return <span key={i}>{line}</span>;
        } else {
            const br = <br key={i + 'br'} />;

            if (line) {
                return [
                    <span key={i}>{line}</span>,
                    br
                ];
            } else {
                return br;
            }
        }
    }
```

**Comment by juanezamudio** [comment]
I agree. Having issues with text just flowing from line to line. It seems every complete sentence for me that ends in a period causes a line break. Any way we could fix this to only line break when line length == container width?

**Comment by juanezamudio** [comment]
Feel like [this issue](https://github.com/One-com/react-truncate/issues/16) is related to this one. @DocCaliban

**Comment by PabloSichert** [comment]
> Not sure why you are adding line breaks here, if my input text didn't contain any line breaks why add them at all?

The line breaks are set explicitly since this module is supposed to calculate the exact position where they should occur.

Did you look into the issue @juanezamudio linked? Do you use a custom font and made sure it is loaded before your first render?
