### ISSUE TITLE
[Feature] Prefix support

### ISSUE THREAD

**Issue by petermikitsh** [One-com/react-truncate#50]
Hi, I'm using your library to implement three-lined Lists, which are part of the material design specification. They look like this:

<img src="https://storage.googleapis.com/material-design/publish/material_v_11/assets/0B6Okdz75tqQsSHRDUllnV1kxSFE/components_lists_keylines_three8.png" alt="Drawing" width="300px" />

It would be nice if I could add a prefix, e.g., like "Ali Connors", in the first list item, that had custom styling. So far, I haven't been able to find a way style only some of the text that is a child of `Truncate`.

The closest I've been able to get truncates the ellipsis, e.g.,

```jsx
<div>
  <b>{'Ali Connors — '}</b>
  <Truncate lines={2} ellipsis="...">
    {description}
  </Truncate>
</div>
```

Renders like this:

<img width="589" alt="screen shot 2017-07-08 at 5 29 40 pm" src="https://user-images.githubusercontent.com/1571918/27990173-141e24cc-6403-11e7-94b0-9603ca8522bb.png">

**Comment by PabloSichert** [comment]
Currently there is no active development for this module, but I would accept a pull request if you want to add this feature.
