### ISSUE TITLE
Avoid omission of subsequent lines on long words 

### ISSUE THREAD

**Issue by soenkehahn** [One-com/react-truncate#51]
This test-case demonstates the current behavior for words that are too long for one line: https://github.com/One-com/react-truncate/blob/master/test/Truncate.js#L227..L239.

We would have expected `react-truncate` to cut off long words and add ellipsis (and do this for every line that has too long words), e.g.:

```
Thereisasuperlo…
so that the next lines won't be
visible
```

Instead of omitting the last two lines.

But maybe this is not really possible due to the way `react-truncate` is implemented. However, this is still a problem for us.

Would it be possible to implement the behavior that we expect? If yes, would you accept a PR? This could of course be guarded by a new option field.

Alternatively, would it be possible to somehow enable word-wrapping that allows breaking of words? I tried to get that to work with the css property `overflow-wrap: break-word;`, but without success.

Any help appreciated.

**Comment by PabloSichert** [comment]
I haven't looked at the problem that way. Would it be possible for you to preprocess the text to shorten those words?

Can you help me understand your problem and elaborate on your use case, why are there words that long in the first place?

**Comment by soenkehahn** [comment]
The words are hyperlinks with a long path and some query parameters. Shortening is not nice, since then users can't actually copy the links and go to the linked website.

Since we stopped using `react-truncate` and put another work-around in place, I'm not really invested in this issue though. Feel free to close.

**Comment by sbt9uc** [comment]
@PabloSichert Can this issue be re-opened? The current behavior described in the test case above seems counter-intuitive. If you have `Thereisasuperlongwordinthefirstline` on the first line I would expect the word to be broken up and continue onto the next line - so that the text that is rendered look would be : 

```
Thereisasuperlon
gwordinthefirst…
```

I am trying to use `react-truncate` but this current behavior goes against my project's requirements.
