### ISSUE TITLE
Support dangerouslySetInnerHTML

### ISSUE THREAD

**Issue by AndersDJohnson** [One-com/react-truncate#57]
Sometimes we have raw HTML and I'm not sure whether this component works when wrapped in another element, e.g., a `<span>`, to which we can apply our `dangerouslySetInnerHTML`.

Currently React gives a warning saying it cannot use this with `children`.

**Comment by Param-Harrison** [comment]
I agree on this issue, we need to support HTML somehow along with the text.

**Comment by nupurkapoor** [comment]
Did you try wrapping it around another element like `<p>` which is then using `dangerouslySetInnerHTML`? I am currently using `react-truncate` in a project, and this is how I have it setup: 

`ExpandCollapse` is a component based on the **Integrated example for toggling "read more" text** section. I export it as a module and then use it in the components I need as 

```
import ExpandCollapse from '../ExpandCollapse'; 
..
<ExpandCollapse>
    <p dangerouslySetInnerHTML={{ __html: this.data }} />
</ExpandCollapse>
```
Works just fine.

**Comment by mbyrne00** [comment]
@nupurkapoor - I'd b interested to hear if it retained your HTML. The example below renders and truncates, however all markup is lost (for example links)
```
<Truncate lines={2}>
  <p dangerouslySetInnerHTML={{ __html: this.data }}/>
</Truncate>
```

**Comment by moubi** [comment]
@AndersDJohnson @Param-Harrison does @nupurkapoor's suggestion solve the issue for you. I would say, if so then go for it.

**Comment by kashifshamaz21** [comment]
@nupurkapoor I tried using a wrapper element with **dangerouslySetInnerHTML** prop, but i'm still not able to get the html markup render. I still get the Truncate component rendering the markup as plain text! Can you show the code of your `ExpandCollapse` component? Appreciate your help.
