### ISSUE TITLE
Padding of parent element ignored for width

### ISSUE THREAD

**Issue by LeopoldLerch** [One-com/react-truncate#58]
Hy
I have div around the truncate-Component. The div has nothing but a padding:5px. However, truncate obviously considers the same width as without padding and jumps into the next line. If I replace the padding with a "margin: 5px", Truncate works as ist should.

The parent of the div (the "grandparent" of the truncate) has also 5px padding. But that seems to be stay respected in regards of the width.

**Comment by taykcrane** [comment]
Any update here? I'm running into the same issue. Except, switching to margin doesn't work for me either...

**Comment by bbthorntz** [comment]
Also experienced issue. Fixed by adding a parent `<div />` element too.

**Comment by moubi** [comment]
Guys let's use the suggested fix. Closing the issue.
