### ISSUE TITLE
TypeError: window.requestAnimationFrame is not a function

### ISSUE THREAD

**Issue by kaizenberg** [One-com/react-truncate#60]
Hi,

When I run **jest**, get this error:
`TypeError: window.requestAnimationFrame is not a function`

<img width="784" alt="screen shot 2017-09-25 at 2 00 07 pm" src="https://user-images.githubusercontent.com/3875593/30820832-8b13e812-a1f9-11e7-95cd-602909522d44.png">

My test library is **enzyme**. And **mount**.

> Note: When I use **shallow** is ok. But I need to use **mount**.

Any idea of how solve this?

Thanks!

**Comment by jordie23** [comment]
Are you using React 16? The latest blog post mentions this:

> React also depends on requestAnimationFrame (even in test environments). A simple shim for test environments would be:
> ```
> global.requestAnimationFrame = function(callback) {
>   setTimeout(callback, 0);
> };
> ```

From: https://reactjs.org/blog/2017/09/26/react-v16.0.html#javascript-environment-requirements

**Comment by kaizenberg** [comment]
@jordie23 Thank for your response, for now, I cant test it. But when I come back to test, I'm going to the response you.

Thanks!
