### ISSUE TITLE
Using string literals in ref attributes is deprecated 

### ISSUE THREAD

**Issue by jordie23** [One-com/react-truncate#62]
Refs should be functions now, not strings.

I think this might be causing issues in React 16, can't seem to get Truncate to work after re-render. It errors and destroys the whole React DOM when you need it to re-render (initial render seems fine?). (In our case, when the window is resized past a breakpoint, we change the number of lines Truncate should wrap to, and then the whole thing dies)

More info from eslint: https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-string-refs.md

**Comment by jordie23** [comment]
PR here https://github.com/One-com/react-truncate/pull/64

**Comment by PabloSichert** [comment]
Thanks!
