### ISSUE TITLE
Problems with React 16.0

### ISSUE THREAD

**Issue by mbrochh** [One-com/react-truncate#63]
First of all, thanks for this awesome component! Works like a charm for us.

It seems like it is not compatible with React 16.0, yet? I just naively tried to update my project and pages without Truncate just work, but pages with Truncate are giving me this error:

```
Uncaught Error: Element ref was specified as a string (target) but no owner was set. You may have multiple copies of React loaded. 
```

I assume this is because Truncate's peer-dependencies? Any chance to bump them to 16.0?

**Comment by Karimit** [comment]
[The integrated example](https://github.com/One-com/react-truncate#integrated-example-for-toggling-read-more-text) stopped working after upgrading to React 16.0.
It breaks when clicking on the (more) link with this error:

> Uncaught DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node

**Comment by jordie23** [comment]
(I'll be making a fork and then pull request soon)

For me two things needed fixing for react 16. The issue I brought up here: https://github.com/One-com/react-truncate/issues/62

And wrapping the text on this line in a span tag: https://github.com/One-com/react-truncate/blob/master/src/Truncate.js#L319

**Comment by PabloSichert** [comment]
Hey guys, thank you very much for reporting.

I haven't been active in this repo for a good amount of time, but I guess some maintenance is needed now and I don't want to be a roadblock here.

I'll look to devote some time now to fix the issues and highly appreciate code contributions.

**Comment by jordie23** [comment]
I'm currently working on a fork and will give some pull requests, but a lot of the testing stuff is out of date and updating them is taking longer than I thought.

**Comment by jordie23** [comment]
PR here https://github.com/One-com/react-truncate/pull/64

**Comment by PabloSichert** [comment]
Updated the [playground](https://www.webpackbin.com/bins/-Kw6QnAkjmv1OD6Of-ZD) with `react@16` and `react-truncate@2.2`.

**Comment by PabloSichert** [comment]
Thanks a lot to everyone involved!

**Comment by jonricaurte** [comment]
@PabloSichert you need to update peer dependencies:

https://github.com/One-com/react-truncate/blob/master/package.json#L34

**Comment by jonricaurte** [comment]
Looks like you removed it when it got squashed:

https://github.com/One-com/react-truncate/pull/65/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R35

vs 

https://github.com/One-com/react-truncate/pull/64/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R35

**Comment by jonricaurte** [comment]
Made a PR: https://github.com/One-com/react-truncate/pull/66/files

**Comment by PabloSichert** [comment]
Hi @jonricaurte thanks for following up. I intentionally reverted the version bump after reading https://github.com/One-com/react-truncate/pull/64#issuecomment-335392053.

`react-truncate` is supposed to still work with `react@15.x`. For that reason `react-truncate` didn't get a major version bump.

Did I miss something?

**Comment by jonricaurte** [comment]
@PabloSichert now it should work for both:

https://github.com/One-com/react-truncate/pull/66/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2

An example of another repo using this:

https://github.com/eiriklv/react-masonry-component/blob/master/package.json#L39

**Comment by jonricaurte** [comment]
Without the above changes, with react 16 you will always get the following in the console:

```warning "react-truncate@2.2.0" has incorrect peer dependency "react@<= 15.x.x".```

**Comment by PabloSichert** [comment]
@jonricaurte I'm sorry, lol. I read that as `>=` instead of `<=`. You're absolutely right.
