### ISSUE TITLE
Truncate target width is < 1px too wide in browser

### ISSUE THREAD

**Issue by cverhelst** [One-com/react-truncate#68]
We can't be 100% certain, but for some reason the resulting width of the text is <1px wider than it's containing span.

We think it may have to do with parent node width precision. Chrome seems to use 3 decimals precision, IE 2 and this works out most of the time, but in a list of < 10 items we 1 instance where it's less than 1 px too wide. When we add the extra pixel, it seems to be fixed.

I think you need to Math.floor() the result of target.parentNode.getBoundingClientRect().width to have more certainty of not exceeding the width of the bouding element.

**Comment by PabloSichert** [comment]
Thanks for the input, that solution could be worth a shot. It's out with [`v2.2.2`](https://github.com/One-com/react-truncate/releases/tag/v2.2.2).

Let me know if it actually fixed your problem!

**Comment by cverhelst** [comment]
Hi, sorry for taking so long to come back on this but I believe it fixed our problem. I couldn't be sure for a while because we still saw the issue popping up from time to time but we now know it's related to that specific element not having a proper width in the first place, leaving a lot of the calculations up to chance depending on what got rendered first. As such, I now can't be 100% certain that our original bug was due to this or not. But I'm sure this change helps by making the text's width not match 100% but leave it a little smaller :). Thanks for the quick fix!

**Comment by PabloSichert** [comment]
Np, thanks for getting back 😄
