### ISSUE TITLE
Call onTruncate when element is resized

### ISSUE THREAD

**Issue by Sventenhaaf** [One-com/react-truncate#76]
I want to truncate the text after a specific element is resized, instead of the browser window. Is that possible? If so, how should I build this?
Example below

![resizeel](https://user-images.githubusercontent.com/8081258/32614020-9c4e9bcc-c56c-11e7-87e0-589177c4e88f.gif)

**Comment by PabloSichert** [comment]
You can assign a ref to the `<Truncate>` child component and call `this.truncate.onResize();` from the parent to refresh it. Also see https://github.com/One-com/react-truncate/issues/49

**Comment by jacklee814** [comment]
@PabloSichert But if the text in the <Truncate> not a component?

**Comment by PabloSichert** [comment]
@jacklee814 Not sure I understand, could you elaborate on what problem that would pose?

**Comment by jacklee814** [comment]
@PabloSichert like that ...

```<Truncate>{this.props.text}</Truncate>```
