### ISSUE TITLE
Unwanted line breaks when using larger than body font size

### ISSUE THREAD

**Issue by mirovelk** [One-com/react-truncate#77]
Hey, I came across an issue when using this component on some text with really large font (larger than body font size). Lines do not fit target element which causes line breaks.

I did some investigation and I found out that ellipsis that are being measured are actually located in document.body. This doesn't seem right, measured width is incorrect. Font and especially font-size can differ a lot at the place that ellipsis are actually rendered after that.

I blame this line:
https://github.com/One-com/react-truncate/blob/373aa7aded3e28c1957bf5c7414bec58f1c33257/src/Truncate.js#L50

When I remove it, everything seems to work perfectly. Ellipsis element is kept in the DOM at the same place that component was used and measured width is correct. What's the reasoning behind having this line? There's a comment that I don't really understand... 

Can we remove this line?

**Comment by mirovelk** [comment]
I've created a pull request here https://github.com/One-com/react-truncate/pull/78

**Comment by arovillard** [comment]
having same issue, hope this gets merged in soon

**Comment by PabloSichert** [comment]
Thanks for the contribution - out on npm with [`v2.2.3`](https://github.com/One-com/react-truncate/releases/tag/v2.2.3)
