### ISSUE TITLE
Forcing recalculation without a window resize

### ISSUE THREAD

**Issue by chacestew** [One-com/react-truncate#89]
Could we expose a way to signal Truncate to re-run `calcTargetWidth`?

My use case is that I have a container that can switch between grid and list layouts. The elements inside will change in width so any Truncates they contain need to recalculate, but because only the parent element is resizing, the window event listener has not fired to inform them.

I'm thinking a prop that could be passed to signal this would work.

```js
<Truncate forceRecalc={layoutHasChanged<Bool>} ... />
```

In the library code this could be handled in `componentWillReceiveProps` to batch the state update prior to rendering:

```js
componentWillReceiveProps({ forceRecalc }) {
  if (forceRecalc) this.calcTargetWidth();
}
```

Looking forward to hearing your thoughts.

**Comment by wtfdaemon** [comment]
Until we get this accepted, having to use the ugly solution of:
```
  componentDidMount() {
    setTimeout(() => {
      window.dispatchEvent(new Event('resize'));
    }, 100);
  }
```

which doesn't work with pre IE-11 (fine for me, though).

**Comment by moubi** [comment]
Hey @wtfdaemon sorry for the late response, it's quite busy on our end. 
Because of the lack of resources we can allocate right now, my suggestion is to stick to the solution you have.

Is it possible in your use case to actually pass different values for the lines `prop` (after some predictions) when switching between views?

**Comment by moubi** [comment]
Ref: https://github.com/One-com/react-truncate/pull/80

**Comment by PabloSichert** [comment]
You can either do

```js
···
recalculate() {
  this.truncate.onResize();
}

render() {
  return (
    <Truncate ref={ref => this.truncate = ref}>···</Truncate>
  );
}
···
```

or use the new `width` property to update the calculation.

Closing in favor of https://github.com/One-com/react-truncate/issues/49. Thanks for contributing!
