### ISSUE TITLE
font-weight is ignoring by canvas in IE11

### ISSUE THREAD

**Issue by NikolaMaster** [One-com/react-truncate#93]
Looks like font-weight is ignored by canvas in IE11 or i am missing something. 
![react-truncate issue](https://user-images.githubusercontent.com/3939781/40920255-af56acb4-6814-11e8-8644-c4924f0987e2.png)

**Comment by enail131** [comment]
Any update on this bug? Experiencing the same issue where it is wrapping incorrectly if there is a font-weight property.

**Comment by PabloSichert** [comment]
![image](https://user-images.githubusercontent.com/4450694/44147734-9246d2a2-a095-11e8-834a-1187b2cc992b.png)

If that piece of code is not working on the browser you are targeting, there is not much we can do (or would officially support).

You can try to file a bug to the browser vendor.
