### ISSUE TITLE
truncating text with wrong width

### ISSUE THREAD

**Issue by jalalat** [One-com/react-truncate#96]
I used lines = 3. It is truncating but at wrong width.
I have shown at the bottom what the whole text looks like.

<img width="960" alt="truncate issue" src="https://user-images.githubusercontent.com/11468630/44145149-57e9aa8e-a082-11e8-8c2d-241ef4ff6c39.png">

**Comment by PabloSichert** [comment]
Did you have a look at the [known issues](https://github.com/One-com/react-truncate#known-issues)?

Could you create a [sandbox](https://codesandbox.io/s/new) where I can reproduce the results?

**Comment by ugo-poly** [comment]
Hi,
I'm having the exact same issue.
I think it's not working because I'm using Trucate inside a Card material ui component.
