### ISSUE TITLE
Compile command doesn't work on Windows

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [One-com/react-truncate#98]
```
C:\Code\react-truncate (master -> origin) (react-truncate@2.4.0)
λ npm run compile

> react-truncate@2.4.0 compile C:\Code\react-truncate
> mkdir lib; babel ./src --out-file ./lib/Truncate.js && BABEL_ENV=CommonJS babel ./src --out-file ./lib/Truncate.CommonJS.js

The syntax of the command is incorrect.
npm ERR! code ELIFECYCLE
```

`;` is not valid in Windows shell. `&&` would be.

**Comment by PabloSichert** [comment]
That would be a bit of a problem, though:

```
$ mkdir foo && echo hi
hi
$ mkdir foo && echo hi
mkdir: foo: File exists
```

Do you know any equivalent for `;` that would work here?

**Comment by joelmukuthu** [comment]
Maybe you can use https://www.npmjs.com/package/npm-run-all?

**Comment by gustavnikolaj** [comment]
`&&` in bash means continue if the last command was successful (status code 0). `mkdir` will return with a non-zero exit code if the directory already exists. `mkdir -p` would allow you to swap over to using `&&`, but I'm not sure if mkdir will work at all.

The npm-run-all package wouldn't necessarily fix that problem, as I suppose it would also error out if the first part of a sequential command chain fails.

There is a project for cross platform unix shell commands called [shelljs](https://github.com/shelljs/shelljs) which is built to solve this exact problem :-)

**Comment by gustavnikolaj** [comment]
```
$ mkdir -p foo && echo hi 
hi
$ mkdir -p foo && echo hi 
hi
```

**Comment by gustavnikolaj** [comment]
There's a version of shelljs wrapped up for this exact use-case called `shx`: https://github.com/shelljs/shx

```json5
{
  // ...
  "scripts": {
    "compile": "shx mkdir -p lib && babel ./src --out-file ./lib/Truncate.js && BABEL_ENV=CommonJS babel ./src --out-file ./lib/Truncate.CommonJS.js"
  },
  "devDependencies": {
    "shx": "*",
    // ...
  },
  // ...
}
```

That will allow `mkdir`to work the sameway as it does on linux/macos on windows. It might be that powershell implements mkdir (it does implement a bunch of linux-like aliases) but I'd not bet money on it supporting -p.

The next problem we will run into is the environment variable. Those will also not work on windows. There's a package for that too called `cross-env`. A fully working example would look like this:

```json5
{
  // ...
  "scripts": {
    "compile": "shx mkdir -p lib && babel ./src --out-file ./lib/Truncate.js && cross-env BABEL_ENV=CommonJS babel ./src --out-file ./lib/Truncate.CommonJS.js"
  },
  "devDependencies": {
    "cross-env": "*",
    "shx": "*",
    // ...
  },
  // ...
}
```

**Comment by gustavnikolaj** [comment]
I sent a PR to address the problem here.

@JoshuaKGoldberg if you get a chance, I would very much appreciate if you could try it out :-)

**Comment by gustavnikolaj** [comment]
The PR referenced above passed review and is now merged to master. I'll close this issue for now, but feel free to open it again if necessary.
